# Використовуємо офіційний образ Node.js 20 або 22
FROM node:22

# Встановлюємо робочу директорію
WORKDIR /app

# Копіюємо package.json та package-lock.json для кешування залежностей
COPY package.json package-lock.json ./

# Встановлюємо системні бібліотеки для `@napi-rs/canvas`
RUN apt-get update && apt-get install -y \
  libcairo2-dev \
  libpango1.0-dev \
  libjpeg-dev \
  libgif-dev \
  libpixman-1-dev \
  libpangocairo-1.0-0 \
  libvips-dev \ # Додайте цю строку
  && rm -rf /var/lib/apt/lists/*


# Встановлюємо залежності через npm
RUN npm ci --omit=dev

# Копіюємо всі файли проєкту
COPY . .

# Відкриваємо порт (якщо бот має API або веб-сервер)
EXPOSE 3000

# Вказуємо команду запуску
CMD ["npm", "start"]
